In [2]:
import numpy as np

In [3]:
a = np.random.random (3) #asking for 3 random numbers
print (a)

[0.36010502 0.62551689 0.328287  ]


In [6]:
b =np.random.random ((3,3)) #prints 3 rows of 3 numbers
print (b)

[[0.29764619 0.03661104 0.37619778]
 [0.61798934 0.20305267 0.20319771]
 [0.72334164 0.2681547  0.25040415]]


In [8]:
c =np.random.rand (3,3,3)
print (c)

[[[0.83987791 0.72212436 0.35072436]
  [0.93877368 0.08928671 0.67445243]
  [0.2996165  0.58415607 0.10588613]]

 [[0.81906831 0.58933439 0.07142987]
  [0.18663757 0.09522258 0.29374297]
  [0.57428071 0.23083106 0.66425024]]

 [[0.5809446  0.19479883 0.46370993]
  [0.76100946 0.4461097  0.57131849]
  [0.44790523 0.13671525 0.82988525]]]


In [11]:
d =np.random.randint (1,10, size =(3,3))
print (d)

[[6 9 2]
 [4 1 6]
 [7 6 3]]


In [15]:
e = ["Pat", "Mary", "Jim", "Sue"]
f = np.random.choice(e, size = (3,3), p=[0.5,0.3,0,0.2])
print (f)

[['Sue' 'Sue' 'Mary']
 ['Mary' 'Pat' 'Pat']
 ['Pat' 'Sue' 'Sue']]
